# Generated by Django 4.0 on 2021-12-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='type',
            field=models.CharField(choices=[('jpg', 'jpg'), ('png', 'png'), ('svg', 'svg')], default='png', max_length=20),
            preserve_default=False,
        ),
    ]
